console.log("Prática 001 de Github");
console.log("Código adicionado da branch console-feature");
console.log("Código adicionado de um clone");
alert("Código adicionado na alert-feature");
alert("Adicionando 1");
alert("Adicionando 2");
alert("Adicionando 3");
alert("Adicionando 4");
alert("Adicionando 5");
alert("Adicionando 6");
alert("Adicionando 7");